version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: streaming_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd123
      POSTGRES_DB: streaming_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: streaming_app
    environment:
      SERVER_ADDRESS: ":8080"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: streaming_db
      POSTGRES_SSL_MODE: disable
    ports:
      - "8080:8080"
    volumes:
      - ./tmp:/app/tmp
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: